language: python
python:
  - "3.6"

env: null
install: 
  - pip install -r requirements.txt
  - pip install coveralls

script: coverage run --source=app app/test.py

repo_token: NEbS5U6ajBfbK8RyWIyGeRXlSyTQKNCeW

after_success:
  - coveralls